name: 'gradleのテストを実行'

on:
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 仮想ブランチにチェックアウト
        uses: actions/checkout@v2


      - name: gradleのライブラリ群をキャッシュ
        uses: actions/cache@preview
        with:
          path: "~/.gradle/caches"
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/build.gradle.kts') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Javaのセットアップ
        uses: actions/setup-java@v2
        with:
          java-version: 11


      - name: ./gradlewに権限を付与
        run: |
          chmod 777 ${{ github.workspace }}/gradlew
      - name: テストを実行
        run: |
          ${{ github.workspace }}/gradlew build
